# fly.toml app configuration file generated for dragee-tailscale on 2023-06-02T12:12:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dragee-tailscale"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
